"""Generate the shared JS/Python parity fixture.

    python -m tools.gen_parity_fixture          # from backend/

The PWA extracts features on the device; the backend holds the authoritative
implementation of the same maths. If the two ever disagree, a patient's baseline — built
from whichever side ran on a given day — stops being comparable to their later sessions,
and every z-score after that point is quietly wrong. Nothing would crash and no test would
fail; the system would just stop working.

So the two implementations are pinned to each other. This script runs the Python
extractors over deliberately awkward inputs and writes the results next to the TypeScript
tests, which assert the JS output matches within tolerance.

Re-run it whenever either implementation changes.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.exam.cognition import extract_attention_speed  # noqa: E402
from app.exam.motor import extract_fine_motor  # noqa: E402

OUT = (Path(__file__).resolve().parents[2]
       / "frontend" / "src" / "lib" / "ondevice" / "__tests__" / "parity_fixture.json")

# Deliberately awkward inputs. A fixture of evenly spaced taps and identical latencies
# would pass against almost any implementation and prove nothing, so these include:
#   - a double-registration 4 ms apart (must be discarded by both sides)
#   - two attention lapses (drive lapse_rate and the median/mean divergence)
#   - a clearly asymmetric pair of hands (the feature the product turns on)
#   - an odd trial count, so percentile interpolation is actually exercised
TAPS_L = [0, 195, 402, 588, 801, 1005, 1009, 1198, 1402, 1610, 1795, 2004, 2210, 2402]
TAPS_R = [0, 402, 795, 1210, 1598, 2005, 2410, 2802, 3215, 3600, 4010, 4405]
DRAG_ERROR = [8.2, 11.5, 9.9, 14.1, 12.0, 10.3]
LATENCIES = [412, 455, 398, 1180, 430, 468, 402, 521, 447, 990, 419, 462]
CHOICE = [702, 745, 688, 1320, 715, 690, 733, 760]


def build() -> dict:
    fine_motor_input = {
        "taps_L": TAPS_L,
        "taps_R": TAPS_R,
        "drag": {"error_px": DRAG_ERROR, "duration_ms": 4200},
    }
    attention_input = {
        "simple_rt": {"latencies_ms": LATENCIES, "misses": 1, "false_starts": 2},
        "choice_rt": [{"latency_ms": v, "correct": v < 900} for v in CHOICE],
        "tmt_a_seconds": 41.5,
        "tmt_a_errors": 1,
    }
    return {
        "_note": (
            "Generated by backend/tools/gen_parity_fixture.py. Do not hand-edit - "
            "re-run the generator so both implementations stay pinned together."
        ),
        "fine_motor": {
            "input": fine_motor_input,
            "expected": extract_fine_motor(fine_motor_input),
        },
        "attention": {
            "input": attention_input,
            "expected": extract_attention_speed(attention_input),
        },
    }


def main() -> None:
    fixture = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2, sort_keys=True), encoding="utf-8")

    print(f"wrote {OUT}")
    print(f"  fine_motor      {len(fixture['fine_motor']['expected'])} features")
    print(f"  attention       {len(fixture['attention']['expected'])} features")
    print(f"  tap_asymmetry   {fixture['fine_motor']['expected']['tap_asymmetry_ratio']:.6f}")
    print(f"  rt_cov          {fixture['attention']['expected']['rt_cov']:.6f}")


if __name__ == "__main__":
    main()
