"""Public, lightweight surface for the isolated Awaaz ASR training runtime."""

from .runtime import (
    APPROVED_PURPOSE,
    PreflightError,
    PrivacySafeRuntimeError,
    RuntimeConfig,
    SplitPlan,
    TrainingRuntimeError,
    build_group_phrase_disjoint_split,
    build_phrase_disjoint_split,
    governance_receipt_signature,
    main,
    normalise_phrase,
    preflight_real_training,
    run_preflight,
    run_synthetic_smoke,
    run_training,
    sha256_directory,
    sha256_file,
    verify_governance_receipt,
)

__all__ = [
    "APPROVED_PURPOSE",
    "PreflightError",
    "PrivacySafeRuntimeError",
    "RuntimeConfig",
    "SplitPlan",
    "TrainingRuntimeError",
    "build_group_phrase_disjoint_split",
    "build_phrase_disjoint_split",
    "governance_receipt_signature",
    "main",
    "normalise_phrase",
    "preflight_real_training",
    "run_preflight",
    "run_synthetic_smoke",
    "run_training",
    "sha256_directory",
    "sha256_file",
    "verify_governance_receipt",
]
