/**
 * JS <-> Python parity — TRD P3 ("add a test comparing JS and Python outputs on the same
 * fixture within tolerance").
 *
 * Why this test is load-bearing rather than tidy-minded:
 *
 * The PWA extracts features on the phone. The backend holds the authoritative
 * implementation of the same maths and runs it when audio or landmarks are available to it.
 * A patient's baseline is built from whichever side ran on each day. If the two drift, the
 * baseline stops being comparable to later sessions, every subsequent z-score is quietly
 * wrong, and nothing crashes and no other test fails. The system just stops working while
 * continuing to produce confident numbers, which is the worst failure mode this product
 * has.
 *
 * The fixture is generated by `backend/tools/gen_parity_fixture.py`. Re-run it after
 * touching either implementation.
 */
import { describe, expect, it } from "vitest";

import fixture from "./parity_fixture.json";
import { extractAttentionSpeed, percentile } from "../attention";
import { asymmetryRatio, extractFineMotor, slope } from "../motor";

/**
 * Tolerance is relative, at 1e-9.
 *
 * Both sides do the same arithmetic in IEEE 754 doubles, so agreement should be near
 * exact; the allowance is for operation ordering, not for genuine algorithmic difference.
 * A looser tolerance would let a real divergence hide inside it.
 */
const REL_TOLERANCE = 1e-9;

function expectClose(actual: number, expected: number, key: string) {
  if (!Number.isFinite(expected)) {
    expect(Number.isFinite(actual), `${key} finiteness`).toBe(false);
    return;
  }
  const tolerance = Math.max(Math.abs(expected) * REL_TOLERANCE, 1e-12);
  expect(Math.abs(actual - expected), `${key}: js=${actual} py=${expected}`)
    .toBeLessThanOrEqual(tolerance);
}

function compare(actual: Record<string, number>, expected: Record<string, number>) {
  // Every feature Python produced must exist on the JS side. A missing feature is not a
  // rounding difference, it is a hole in the on-device path.
  for (const [key, value] of Object.entries(expected)) {
    expect(actual, `missing feature ${key}`).toHaveProperty(key);
    expectClose(actual[key], value as number, key);
  }
  // ...and the JS side must not invent features the server does not know about, since
  // those would never be baselined or scored.
  for (const key of Object.keys(actual)) {
    expect(expected, `unexpected extra feature ${key}`).toHaveProperty(key);
  }
}

describe("M7 fine motor", () => {
  const { input, expected } = fixture.fine_motor;

  it("matches the Python implementation feature for feature", () => {
    compare(
      extractFineMotor(input as Parameters<typeof extractFineMotor>[0]) as Record<string, number>,
      expected as Record<string, number>,
    );
  });

  it("discards a double-registration the same way Python does", () => {
    // The fixture's left hand contains taps 4 ms apart from a bouncing touch event.
    const result = extractFineMotor(input as Parameters<typeof extractFineMotor>[0]);
    expect(result.tap_count_L).toBe((expected as Record<string, number>).tap_count_L);
  });

  it("computes the asymmetry ratio that separates a lesion from bilateral slowing", () => {
    const result = extractFineMotor(input as Parameters<typeof extractFineMotor>[0]);
    expectClose(
      result.tap_asymmetry_ratio,
      (expected as Record<string, number>).tap_asymmetry_ratio,
      "tap_asymmetry_ratio",
    );
    expect(result.tap_asymmetry_ratio).toBeGreaterThan(0.3);
  });

  it("returns invalid rather than guessing when there are too few taps", () => {
    expect(extractFineMotor({ taps_L: [0, 100], taps_R: [0, 100] }).valid).toBe(0);
  });
});

describe("M10 attention and speed", () => {
  const { input, expected } = fixture.attention;

  it("matches the Python implementation feature for feature", () => {
    compare(
      extractAttentionSpeed(input as Parameters<typeof extractAttentionSpeed>[0]) as Record<string, number>,
      expected as Record<string, number>,
    );
  });

  it("computes rt_cov, the sensitive marker, identically", () => {
    const result = extractAttentionSpeed(input as Parameters<typeof extractAttentionSpeed>[0]);
    expectClose(result.rt_cov, (expected as Record<string, number>).rt_cov, "rt_cov");
  });

  it("returns invalid rather than guessing when there are too few trials", () => {
    expect(extractAttentionSpeed({ simple_rt: { latencies_ms: [400, 420] } }).valid).toBe(0);
  });
});

describe("shared numeric helpers", () => {
  it("percentile interpolates the way numpy.percentile does by default", () => {
    const values = [1, 2, 3, 4];
    expect(percentile(values, 0)).toBe(1);
    expect(percentile(values, 100)).toBe(4);
    expect(percentile(values, 50)).toBeCloseTo(2.5, 12);
    expect(percentile(values, 25)).toBeCloseTo(1.75, 12);
    expect(percentile(values, 75)).toBeCloseTo(3.25, 12);
  });

  it("slope matches a least-squares fit against the index", () => {
    expect(slope([1, 2, 3, 4])).toBeCloseTo(1, 12);
    expect(slope([4, 3, 2, 1])).toBeCloseTo(-1, 12);
    expect(slope([5, 5, 5])).toBeCloseTo(0, 12);
    expect(slope([7])).toBe(0);
  });

  it("asymmetry ratio is scale-free and zero when the sides match", () => {
    // Asserted to 9 places, not 12. Both implementations add a 1e-9 epsilon to the
    // denominator so that a patient who records zero taps on both hands yields 0 rather
    // than NaN, and that epsilon perturbs the result at about 4e-11. The epsilon is the
    // point: the two sides carry the *same* one, so they agree exactly with each other
    // even though neither matches textbook arithmetic to the last bit.
    expect(asymmetryRatio(5, 5)).toBeCloseTo(0, 9);
    expect(asymmetryRatio(6, 3)).toBeCloseTo(1 / 3, 9);
    // Scale-free: doubling both sides leaves it unchanged.
    expect(asymmetryRatio(12, 6)).toBeCloseTo(asymmetryRatio(6, 3), 9);
    // And the guard actually holds when there is nothing to divide by.
    expect(asymmetryRatio(0, 0)).toBe(0);
    expect(Number.isFinite(asymmetryRatio(0, 0))).toBe(true);
  });
});
