/**
 * Why the third gate exists, drawn: symmetric decline against one-sided decline.
 *
 * The Parkinson's section was the only part of the argument carried by prose alone, and it
 * is the hardest part to accept — three domains agreeing really does look like proof. The
 * discriminator is not the size of the change, it is whether the change has a side, and
 * that is a picture: the same three domains deviating by the same amount, once with the
 * left and right bars matched and once with them split.
 *
 * Both panels are shown at once rather than morphing between them, for the same reason the
 * population panels are: a comparison you can look back and forth between is read faster
 * than one you have to scroll to see the other half of.
 */
import { DURATION, EASE, useInView, usePrefersReducedMotion } from "@/lib/motion";

interface Row { label: string; note?: string; left: number; right: number }

/** Bars are |robust z|; 2.0 is the deviation threshold, and the axis runs to 3.2. */
const SYMMETRIC: Row[] = [
  { label: "Face", left: 2.5, right: 2.45 },
  // Voice is drawn matched in BOTH panels on purpose: speech has no left/right axis, so it
  // can never be one-sided. It corroborates a focal finding; it can never establish one.
  { label: "Voice", note: "no side", left: 2.6, right: 2.6 },
  { label: "Hand", left: 2.4, right: 2.35 },
];

const LATERAL: Row[] = [
  { label: "Face", left: 2.7, right: 0.5 },
  { label: "Voice", note: "no side", left: 2.55, right: 2.55 },
  { label: "Hand", left: 2.6, right: 0.6 },
];

const MAX = 3.2;

/**
 * Literal class names, not `text-${tone}`.
 *
 * Tailwind scans source text; a class assembled at runtime is invisible to it and is only
 * ever generated by accident, because the same literal happens to appear in another file.
 * Both of these currently do — which is exactly why this looked fine and was still wrong.
 */
const VERDICT_CLASS = {
  atypical: "text-atypical",
  alert: "text-alert",
} as const;

function Panel({
  title, caption, rows, verdict, tone, shown, delay,
}: {
  title: string; caption: string; rows: Row[];
  verdict: string; tone: "atypical" | "alert"; shown: boolean; delay: number;
}) {
  return (
    <div className="rounded-2xl border border-line bg-background p-5 text-left sm:p-6">
      <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">{title}</p>
      <p className="mt-2 text-[15px] leading-relaxed text-muted-foreground">{caption}</p>

      <div className="mt-5 space-y-3">
        <div className="flex items-center gap-3 font-mono text-[9px] uppercase tracking-[0.16em] text-muted-foreground">
          <span className="w-[4.5rem] shrink-0" />
          <span className="flex-1 text-right">left</span>
          <span className="w-px" />
          <span className="flex-1">right</span>
        </div>
        {rows.map((row, i) => (
          <div key={row.label} className="flex items-center gap-3">
            <span className="w-[4.5rem] shrink-0 text-[12px] leading-tight text-muted-foreground">
              {row.label}
              {row.note && (
                <span className="block font-mono text-[9px] uppercase tracking-wider opacity-70">
                  {row.note}
                </span>
              )}
            </span>
            {/* Mirrored pair: the eye compares two bar ENDS, which is far easier than
                comparing two lengths that start from the same edge. */}
            <span className="flex flex-1 justify-end">
              <span
                className="block h-2.5 rounded-l-full"
                style={{
                  width: shown ? `${(row.left / MAX) * 100}%` : 0,
                  background: row.left < 2 ? "hsl(var(--muted))"
                    : row.note ? `hsl(var(--${tone}) / 0.45)` : `hsl(var(--${tone}))`,
                  transition: `width ${DURATION.slow}ms ${EASE.out} ${delay + i * 90}ms`,
                }}
              />
            </span>
            <span className="h-4 w-px bg-line" />
            <span className="flex flex-1">
              <span
                className="block h-2.5 rounded-r-full"
                style={{
                  width: shown ? `${(row.right / MAX) * 100}%` : 0,
                  background: row.right < 2 ? "hsl(var(--muted))"
                    : row.note ? `hsl(var(--${tone}) / 0.45)` : `hsl(var(--${tone}))`,
                  transition: `width ${DURATION.slow}ms ${EASE.out} ${delay + i * 90}ms`,
                }}
              />
            </span>
          </div>
        ))}
      </div>

      <p
        className={`mt-5 font-mono text-[11px] tracking-[0.16em] ${VERDICT_CLASS[tone]}`}
        style={{
          opacity: shown ? 1 : 0,
          transition: `opacity ${DURATION.medium}ms ${EASE.out} ${delay + 420}ms`,
        }}
      >
        {verdict}
      </p>
    </div>
  );
}

export function SymmetryDiagram() {
  const reduced = usePrefersReducedMotion();
  const { ref, inView } = useInView<HTMLDivElement>({ rootMargin: "0px 0px -18% 0px" });
  const shown = reduced || inView;

  return (
    <div ref={ref} className="grid gap-4 md:grid-cols-2">
      <Panel
        title="Parkinson's"
        caption="Three domains deviate, persistently, by the same amount on both sides."
        rows={SYMMETRIC}
        verdict="SYMMETRIC → PATTERN_ATYPICAL, NOT AN ALERT"
        tone="atypical"
        shown={shown}
        delay={0}
      />
      <Panel
        title="A stroke"
        caption="The same three domains, the same magnitude — but the deviation has a side."
        rows={LATERAL}
        verdict="ONE-SIDED → GATE 3 SATISFIED"
        tone="alert"
        shown={shown}
        delay={260}
      />
    </div>
  );
}
